"""Markdown daily report generator — the artifact the daily agent pushes."""

from .backtest import Stats
from .strategy import (BREAKOUT_UNCONFIRMED, BUY, EXIT, STATE_ORDER, UPTREND,
                       WATCH, Signal)

DISCLAIMER = (
    "> **Human review required.** Signals are generated by fixed rules on "
    "end-of-day data. They are research output, not financial advice. "
    "Position sizes assume the configured account size and 1% risk per trade. "
    "Responsibility is yours.\n")


def _fmt(x: float, nd: int = 2) -> str:
    return f"{x:,.{nd}f}"


def build(signals: list[Signal], stats: dict[str, Stats], run_date: str,
          account_size: float, risk_pct: float) -> str:
    signals = sorted(signals, key=lambda s: STATE_ORDER.index(s.state))
    actionable = [s for s in signals if s.state in (BUY, BREAKOUT_UNCONFIRMED, WATCH, EXIT)]

    lines = [
        f"# Fable Rules — Daily Signals · {run_date}",
        "",
        DISCLAIMER,
        f"Account basis: **${account_size:,.0f}**, risking **{risk_pct:g}%** "
        f"(${account_size * risk_pct / 100:,.0f}) per trade. "
        "Strategy: close above 20-day resistance on above-average volume; "
        "stop at the 10-day low; exit on a close below 20-day support.",
        "",
        "## Signal board",
        "",
        "| Symbol | State | Close | 1d % | Entry trigger | Stop | Dist to trigger | Vol vs 20d | RSI14 |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for s in signals:
        lines.append(
            f"| **{s.symbol}** | {s.state} | {_fmt(s.close)} | {s.change_1d:+.1f}% "
            f"| {_fmt(s.resistance)} | {_fmt(s.stop)} | {s.dist_to_trigger_pct:+.1f}% "
            f"| {s.volume_ratio:.1f}x | {s.rsi14:.0f} |")

    if actionable:
        lines += ["", "## Trade plans", ""]
        for s in actionable:
            t = " · ".join(f"{lbl} = {_fmt(px)}" for lbl, px in s.targets)
            how = ("already triggered — entry at market/close" if s.state == BUY
                   else "buy-stop just above the trigger" if s.state == WATCH
                   else "wait for a volume-confirmed close" if s.state == BREAKOUT_UNCONFIRMED
                   else "exit level")
            lines += [
                f"### {s.symbol} — {s.state}",
                "",
                f"{s.note}",
                "",
                f"- Entry: **{_fmt(s.entry)}** ({how})",
                f"- Stop loss: **{_fmt(s.stop)}** (risk {_fmt(s.risk_per_share)}/unit)",
                f"- Targets: {t or 'n/a'}",
                f"- Size: **{s.size_label}** ≈ ${s.shares * s.entry:,.0f} exposure, "
                f"${s.risk_dollars:,.0f} at risk",
                "",
            ]
    else:
        lines += ["", "_No actionable setups today — patience is a position._", ""]

    lines += ["", "## Rule backtest on this watchlist (last ~12 months, indicative)", "",
              "| Symbol | Trades | Win rate | Avg R | Total return | Max DD | Profit factor |",
              "|---|---:|---:|---:|---:|---:|---:|"]
    for s in signals:
        st = stats.get(s.symbol)
        if not st:
            continue
        pf = "∞" if st.profit_factor >= 999 else f"{st.profit_factor:.2f}"
        lines.append(
            f"| {s.symbol} | {st.trades} | {st.win_rate:.0f}% | {st.avg_r:+.2f} "
            f"| {st.total_return_pct:+.1f}% | {st.max_drawdown_pct:.1f}% | {pf} |")

    lines += ["", "---", "",
              "*Generated by the Fable Rules daily agent. Edit the watchlist in "
              "`tradebot/config.py`; the Pine Script mirror of these rules lives "
              "in `pine/fable_rules.pine`.*", ""]
    return "\n".join(lines)
